name: CI Workflow
on: [push]
jobs:
  build:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout code
      - run: echo "Hello world"
        name: Echo greeting 
      - run: ls -la
        name: List files
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '21'
      - name: Grant execute permission for gradlew
        run: | 
            chmod +x gradlew
            ./gradlew build
            ./gradlew bootJar
      - name: Build Docker image
        run: |
            docker build -t cloudcamp-cicd .
            



    
